# Generated by Django 5.2.3 on 2025-06-20 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionfisica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_entrenamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannutricion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progreso',
            name='evaluacion_referencia',
            field=models.ForeignKey(blank=True, help_text='Evaluación física de referencia para este progreso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evaluacionfisica'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL),
        ),
    ]
