# Generated by Django 5.2.3 on 2025-06-15 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionfisica',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='evaluacionfisica',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='evaluacionfisica',
            name='postura',
        ),
        migrations.RemoveField(
            model_name='planentrenamiento',
            name='duracion_min',
        ),
        migrations.AddField(
            model_name='evaluacionfisica',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('perder_grasa', 'Perder grasa'), ('tonificar', 'Tonificar'), ('ganar_musculo', 'Ganar músculo'), ('salud_general', 'Mejorar salud general')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='foto_progreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imagencorporal'),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.imagencorporal'),
        ),
        migrations.AlterField(
            model_name='evaluacionfisica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagencorporal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_corporales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planentrenamiento',
            name='dias_por_semana',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='planentrenamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_entrenamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plannutricion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL),
        ),
    ]
